### ISSUE TITLE
Formating Issues

### ISSUE THREAD

**Issue by IsaiahPatton** [CodeCrafter47/Rainbow#22]
There is Formating issues in Rainbow, (Mainly in PluginReference)

Less then min fix for tabs:
In Notepad++:
Search -> Find in Files -> Replace All -> DONE

also most starting brackets are on new lines, example:

public String IamAString()
{ <--- should be on above line!
    return "I like Rainbows!"
}

according to [CodeBeautify's Java beautifier](http://codebeautify.org/javaviewer) just moving the bracket to the same line would save 1 byte per bracket, it might seem like a small difference but you save that **per** bracket.

also according to CodBeautify, removing white spaces would save 5 bytes per whitepace.

- [ ] Replace Tabs
- [ ] Remove whitepaces.
- [ ] Move starting brackets to same line.

**Comment by CodeCrafter47** [comment]
I think formatting is about code being easy to read not about saving disk space, so that is not a valid argument. That being said I fail to see a reason **why** we should change the formatting.

Now here's a good reason why we shouldn't enforce a strict style guide: By doing so the first response to every future PR's will be complaints about the formatting which isn't productive at all and discourages people. I think it's fine as long as the code is readable. 

Regarding the opening brackets, in the PluginReference they are on a new line, because Joe prefers it that way, in the rainbow server code they are not, because I've written that code and that's how I prefer it. So I'd say there is some system behind the formatting.

Also I prefer whitespaces to tabs, because tabs are interpreted differently by different applications, for example Github interprets a tab as 8 spaces, whereas most IDE's are configured to interpret a tab as 4 spaces.

The Java version we use is unrelated to the code formatting, so if you want to discuss that please create a new issue.
